// See https://aka.ms/new-console-template for more information
Console.Write("Namn: ");
string firstName = Console.ReadLine();
Console.Write("Age: ");
string age = Console.ReadLine();
int ageInt = int.Parse(age);
string heighttext = "1,75";
double.TryParse(heighttext, out double height);
Console.WriteLine("Namn: " + firstName);
Console.WriteLine("Ålder: " + age);
Console.WriteLine("Längd: " + height);
decimal price = 999.99m;
bool isAvailable = true;
Console.WriteLine("Pris: " + price);
Console.WriteLine("Tillgänglig: " + isAvailable);
char grade = 'A';
byte roomNumber = 3;
Console.WriteLine("Betyg: " + grade);
Console.WriteLine("Sal: " + roomNumber);
int systernage = ageInt + 2;
Console.WriteLine("Systerns ålder: " + systernage);
Console.Write("Ange priset för din lunch: ");
string breakfastInput = Console.ReadLine();
decimal breakfast = Convert.ToDecimal(breakfastInput);
int priceOre = (int)(breakfast * 100);
Console.WriteLine("Pris i öre: " + priceOre);
Console.WriteLine("Pris i öre: {0}", priceOre); 
Console.WriteLine($"Pris i öre: {priceOre}");
